### ISSUE TITLE
Issue, need to add support for interactive sudo password when using Sudo

### ISSUE THREAD

**Issue by ChrisPRobinson** [wingedpig/loom#3]
I am working on a pull request to add support for setting the sudo password if it is prompted for. Would a feature like this be accepted?

**Comment by ChrisPRobinson** [comment]
Are you working on this library much or do it have the functionality you need and its working so is that why there hasn't been much active work?

**Comment by wingedpig** [comment]
Hi, yes, that would be accepted. We use loom all the time at groups.io; it does everything we need which is why there hasn't been any development. But I'd be happy to accept your pull request.

**Comment by ChrisPRobinson** [comment]
Great, I'll make a pull request soon.

**Comment by ChrisPRobinson** [comment]
I made the pull request, it was a bit more complex than I expected. Take a look when you get a chance and let me know any changes/improvements/additional tests you want made/included. 

One thing to note is obviously your team doesn't need this feature, its possible that a flag in config could be added to turn this feature on and off, and by default it will be false, this way the feature will work as it normally does when running in your case but the additional functionality can be turned on if needed.

**Comment by ChrisPRobinson** [comment]
pull request in. Thanks
